/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    copy: typeof import('./../components/Tunnel copy.vue')['default']
    DeviceGroup: typeof import('./../components/DeviceGroup.vue')['default']
    DeviceIcon: typeof import('./../components/DeviceIcon.vue')['default']
    Display: typeof import('./../components/Display.vue')['default']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    Hole: typeof import('./../components/Hole.vue')['default']
    IEpHomeFilled: typeof import('~icons/ep/home-filled')['default']
    IEpLocation: typeof import('~icons/ep/location')['default']
    README: typeof import('./../components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Stake: typeof import('./../components/Stake.vue')['default']
    TheFooter: typeof import('./../components/TheFooter.vue')['default']
    TheInput: typeof import('./../components/TheInput.vue')['default']
    Tunnel: typeof import('./../components/Tunnel.vue')['default']
    VideoBox: typeof import('./../components/VideoBox.vue')['default']
  }
}
